fn main() -> Result<(), std::io::Error> {
    s3::main()
}
